### ISSUE TITLE
Any way to pass a licence automatically at install

### ISSUE THREAD

**Issue by hussfelt** [boxen/puppet-onepassword#5]
We're running boxen at our organisation and I'd hate to need to add the licence-key to each and every install... :-)

Our repository is private here, so I wouldn't mind adding it to my manifests at my boxen repo...

Is there any plans of supporting this or is it already supported somehow?

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
